# Generated by Django 4.2.15 on 2024-08-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('medicine', models.CharField(max_length=300)),
                ('test_date', models.DateField()),
            ],
        ),
    ]
