# Generated by Django 4.2.15 on 2024-08-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.JSONField(),
        ),
    ]
