# Generated by Django 4.2.15 on 2024-08-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoruser',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
