# Generated by Django 4.2.11 on 2024-08-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctoruser_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('medicine', models.JSONField()),
                ('test_date', models.DateField()),
            ],
        ),
    ]
