# Generated by Django 4.2.11 on 2024-08-22 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0004_emailgeneration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoruser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='doctoruser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='username',
        ),
        migrations.AddField(
            model_name='doctoruser',
            name='d_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
