# Generated by Django 4.2.11 on 2024-08-22 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0005_alter_doctoruser_options_alter_doctoruser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruser',
            name='d_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
