# Generated by Django 4.2.11 on 2024-08-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_doctoruser_d_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoruser',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='doctoruser',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctoruser',
            name='starting_time',
            field=models.TimeField(null=True),
        ),
    ]
